### ISSUE TITLE
Error with yaml-cpp.lib

### ISSUE THREAD

**Issue by exitss** [ByteCorum/DragonBurn#1]
![image](https://github.com/ByteCorum/DragonBurn/assets/67079527/75538539-bf4a-4b00-b3a6-68a2e2135789)

**Comment by ByteCorum** [comment]
Thx for feedback, I'll fix it

**Comment by ByteCorum** [comment]
Fixed in new commit https://github.com/ByteCorum/DragonBurn/commit/34a32d67bd631713d0632152506b94ff5cd0084d
