### ISSUE TITLE
Offsets update failed

### ISSUE THREAD

**Issue by Mid0aria** [ByteCorum/DragonBurn#120]
I think a2x's github account has been closed because neither the profile can be view in nor the cs2-dumper repository, i.e. offsets gg

https://github.com/a2x/cs2-dumper

**Comment by ByteCorum** [comment]
Yeah I see now u can compile WIP brunch it will work up to next cs2 update

**Comment by Mid0aria** [comment]
It would be nice if we could manually add the offsets from an external json because I have cs2 dumper and it works

**Comment by ByteCorum** [comment]
k I'll do it asap

**Comment by Mid0aria** [comment]
thx

**Comment by ByteCorum** [comment]
can u give me cs-dumper source?

**Comment by Mid0aria** [comment]
i just have .exe

**Comment by ByteCorum** [comment]
K any way it will work

**Comment by ByteCorum** [comment]
I won't change offsets getting system for now I'll just use cs dumper to get them and post

**Comment by ByteCorum** [comment]
I'll add it asap, also how to use cs dumper cuz I can't look at readme now

**Comment by Mid0aria** [comment]
open game then open csdumper.exe

**Comment by ByteCorum** [comment]
Should I open game with -insecure?

**Comment by Mid0aria** [comment]
na u can open with default settings

**Comment by ByteCorum** [comment]
Will I get banned?

**Comment by Gintamashiichan** [comment]
replace with https://github.com/sezzyaep/CS2-OFFSETS, in Offsets.cpp
from line 95-97
```
      const std::string offsetsUrl = "https://raw.githubusercontent.com/a2x/cs2-dumper/main/output/offsets.json";
      const std::string buttonsUrl = "https://raw.githubusercontent.com/a2x/cs2-dumper/main/output/buttons.json";
      const std::string client_dllUrl = "https://raw.githubusercontent.com/a2x/cs2-dumper/main/output/client_dll.json";
```
to
```
       const std::string offsetsUrl = "https://raw.githubusercontent.com/sezzyaep/CS2-OFFSETS/main/offsets.json";
       const std::string buttonsUrl = "https://raw.githubusercontent.com/sezzyaep/cs2-dumper/main/output/buttons.json";
       const std::string client_dllUrl = "https://raw.githubusercontent.com/sezzyaep/cs2-dumper/main/output/client_dll.json";
```

**Comment by ByteCorum** [comment]
Thx but he just updated offsets, and I already have cs-dumper and storage for offsets

**Comment by ByteCorum** [comment]
Look at wip brunch code
