### ISSUE TITLE
error with driver

### ISSUE THREAD

**Issue by alrohax** [ByteCorum/DragonBurn#151]
I load the driver and it says success in kdmapper but on the cheat it doesnt work, it worked yesterday but not now

**Comment by Lmaotime** [comment]
Looking at the provided screenshots on discord, It seems like the driver wasn't actually loaded successfully in kdmapper (Can't find pattern error). Try opening cmd or powershell as admin and enabling test mode using "bcdedit /set testsigning on" and reboot your pc. If you got an error running the command related to not having permission/access, try disabling Secure Boot in your BIOS.

**Comment by ByteCorum** [comment]
restart pc or smth
