### ISSUE TITLE
kdmapper problem

### ISSUE THREAD

**Issue by KeReM0699** [ByteCorum/DragonBurn#152]
Yesterday, when I ran DragonBurn.exe on my computer for the first time, DragonBurn.exe was working. However, today, when I tried to run it again, I received the following error in the DragonBurn.exe console.

I am sharing the outputs below, and I thank you in advance for your help.

DragonBurn.exe  console:
[+]Your cheat version is up to date
[+]Offsets updated
[X]Failed to connect to kernel mode driver
Press any key to continue . . .

kdmapper console : 

[<] Loading vulnerable driver, Name: YLIsKxBsXky
[+] NtLoadDriver Status 0x0
[+] PiDDBLock Ptr 0xfffff8047776b448
[+] PiDDBCacheTable Ptr 0xfffff8047776b584
[+] PiDDBLock Locked
[+] Found Table Entry = 0xFFFF8E8F8B404AF0
[+] PiDDBCacheTable Cleaned
[+] g_KernelHashBucketList Found 0xFFFFF80479EC3088
[+] g_HashCacheLock Locked
[+] Found In g_KernelHashBucketList: YLIsKxBsXky
[+] g_KernelHashBucketList Cleaned
[+] MmUnloadedDrivers Cleaned: YLIsKxBsXky
[+] WdFilter.sys not loaded, clear skipped
[+] Image base has been allocated at 0xFFFFBD8E3BBE8000
[+] Skipped 0x1000 bytes of PE Header
[+] Fixing stack cookie
[<] Calling DriverEntry 0xFFFFBD8E3BBE8140
[+] Callback example called
[+] DriverEntry returned 0xc0000035
[<] Unloading vulnerable driver
[+] NtUnloadDriver Status 0x0
[+] Vul driver data destroyed before unlink
[+] success
Press any key to continue . . .

![dragonburn](https://github.com/user-attachments/assets/49aede6b-9c54-42db-93ba-b99dcf23ab45)

**Comment by Lmaotime** [comment]
Try restarting your PC.
