### ISSUE TITLE
Crashes randomaly

### ISSUE THREAD

**Issue by dyinginslowmotion** [ByteCorum/DragonBurn#53]
Hello i just built this by my self and it crashes randomaly after running for 10-20 seconds

**Comment by ByteCorum** [comment]
I think this is due to the fact that I have not updated the offsets for a long time. I'm already working on the update

**Comment by ByteCorum** [comment]
I need to completely rework the system for receiving offsets, it will take a little longer than expected

**Comment by dyinginslowmotion** [comment]
okay, take your time

**Comment by ByteCorum** [comment]
I fixed it here #55. Now it should work😊

**Comment by dyinginslowmotion** [comment]
thanks
