### ISSUE TITLE
Doesnt work!

### ISSUE THREAD

**Issue by LinuxClient** [ByteCorum/DragonBurn#56]
Client opens with gui and all but features dont work!

**Comment by ByteCorum** [comment]
After the recent update, such problems should have resolved. I gonna look for it. Thx

**Comment by ByteCorum** [comment]
Sry, my bad. I found the problem, It gonna be fixed asap

**Comment by ByteCorum** [comment]
I fixed it here https://github.com/ByteCorum/DragonBurn/pull/57. Now it should work😊

**Comment by LinuxClient** [comment]
Thank you!
