### ISSUE TITLE
Triggerbot not working

### ISSUE THREAD

**Issue by kura6789** [ByteCorum/DragonBurn#60]
How to fix triggerbot?
after this line:
 if (!ProcessMgr.ReadMemory(LocalEntity.Pawn.Address + Offset::Pawn.iIDEntIndex, uHandle))
std::cout << uHandle << std::endl;

uHandle is still =0

**Comment by kura6789** [comment]
it stopped working after last offset update

**Comment by ByteCorum** [comment]
I gonna fix it asap. Thx

**Comment by ByteCorum** [comment]
Idk for me just everything is fine

**Comment by ByteCorum** [comment]
Try now

**Comment by kura6789** [comment]
still not working. I think u didnt change anything in code insted of new offsets
