### ISSUE TITLE
Problems that arise

### ISSUE THREAD

**Issue by lizifan1** [ByteCorum/DragonBurn#61]
ImGui robot program display error, font switching error display?
![微信截图_20240529210752](https://github.com/ByteCorum/DragonBurn/assets/82872626/43d6981f-257d-4bfd-921f-8c618c0f09a0)

**Comment by ByteCorum** [comment]
Omg, I gonna fix it asap

**Comment by ByteCorum** [comment]
Try [this](https://exploratory.io/note/exploratory/Enabling-UTF-8-on-Windows-hYc3yWL0)

**Comment by lizifan1** [comment]
![_20240608150029](https://github.com/ByteCorum/DragonBurn/assets/82872626/62da412c-94f8-46e8-a0fc-8ee76c04a6a0)
Still like this, maybe there's a problem with the imgui

**Comment by ByteCorum** [comment]
the text in the window has been corrected, but what’s happening on your screen is the first time I’ve seen something like this

**Comment by ByteCorum** [comment]
I think it detected your screen incorrectly

**Comment by ByteCorum** [comment]
can you write what kind of gpu and screen you have?

**Comment by lizifan1** [comment]
NVIDIA GeForce RTX 4060 Laptop GPU
2560x1600 240hz
13th_Gen_Intel(R)_Core(TM)_i5-13500HX\10。

**Comment by ByteCorum** [comment]
fixed
