### ISSUE TITLE
Undetected ...

### ISSUE THREAD

**Issue by Leksa667** [ByteCorum/DragonBurn#69]
Undetected while you read and write the memory directly in user-mode that would surprise me greatly given the VAC update

**Comment by ByteCorum** [comment]
It only reads memory

**Comment by Leksa667** [comment]
My bad yes, but regarding the VAC update and the ban waves I think single user mode is pretty simple and I think it will be detected very quickly

**Comment by ByteCorum** [comment]
> My bad yes, but regarding the VAC update and the ban waves I think single user mode is pretty simple and I think it will be detected very quickly

Mb I'll transfer it to kernel mode
