### ISSUE TITLE
i cant find how to open/close the menu?

### ISSUE THREAD

**Issue by letmedie-dbg** [ByteCorum/DragonBurn#77]
i cant find how to open/close the menu?

**Comment by ByteCorum** [comment]
END key,
![end-key](https://github.com/user-attachments/assets/461c45e5-dfab-4756-9577-cf83118b2e7b)

**Comment by ByteCorum** [comment]
Now it's in readme
https://github.com/ByteCorum/DragonBurn/commit/56f88529466bfe4d37a9f1e2f1b85b8f5d0764fc
